### ISSUE TITLE
Make groups visible to full cluster

### ISSUE THREAD

**Issue by smoyte** [gather-community/gather#1023]

**Comment by kenatsun** [comment]
Aren't they already visible?  For example, the Zoning Ordinance Action Group (https://sunward.gather.coop/groups/465), managed by Touchstoners, is visible (and joinable) to me as a Sunwardian.

**Comment by smoyte** [comment]
@kenatsun good question! Currently only groups that involve your community are visible. The zoag group lists all three communities. I got a request to make _all_ groups accessible (not joinable or editable, just readable) since it would help cross-community collaboration. It seemed to make sense to me and I couldn't see any downsides so going to try it out.

**Comment by kenatsun** [comment]
Only downside I can see is if for some reason the managers of a community A group didn't want anything about the group (even its existence?) to be visible to community B.  Will this ever arise?  I don't know, but I think I recall that there have been concerns about having data about members (or particular members) of a community be visible to other communities in the same cluster.  (I don't recall how that has played out.)  Maybe let 'visible' be the default, but give a setting to let that group's manager make it invisible?

**Comment by smoyte** [comment]
All users are already visible across the cluster, except for children. And children can't be group members currently.
