### ISSUE TITLE
Don't send statement emails to inactive household members if there are still some active ones

### ISSUE THREAD

**Issue by smoyte** [gather-community/gather#1034]

**Comment by smoyte** [comment]
See AccountMailer#statement_mail. Perhaps add `include_inactive: :only_if_no_active_household_members` or some such.

**Comment by willn** [comment]
Great Oak is experiencing this issue. An adult child who has moved out and has a deactivated account is still receiving account statements. Additionally, her ex-boyfriend who only lived with us briefly was given access to sign up for meals as part of their household within Gather is also getting these messages.

As a temporary workaround, I will be deleting his email address, and will be removing the adult child from their household.

**Comment by smoyte** [comment]
This is fixed now
