### ISSUE TITLE
Duplicate period

### ISSUE THREAD

**Issue by smoyth** [gather-community/gather#212]
_Originally created by **Tom Smyth** at **2018-01-17 15:44**, migrated from [redmine-#7847](https://redmine.sassafras.coop/issues/7847)_

**Comment by smoyth** [comment]
* **Tags** set to _work_

_By **Tom Smyth** at **2018-01-17 20:45**_

**Comment by smoyth** [comment]
* **Priority** changed from _?_ to _4_

_By **Tom Smyth** at **2018-03-16 13:18**_

**Comment by mountainaireman** [comment]
I would really love to see this one happen.
