### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by smoyte** [gather-community/gather#473]
* Needed for Great Oak truck issue

Approach 1

* Add UserPropertySet model/table much like Community/Cluster, with hard-coded columns like can_use_truck
* In Community, have a field called enabled_user_properties, editable only by superadmins, where you whitelist all the UserPropertySet fields that are applicable to this community
* Then you still get to use Rails validation, etc., and it's so much less confusing than Approach 2

Approach 2

* See notes in Evernote
* User should be able to have custom data values
* The custom data schema can be defined per-community (see the Per-community Settings issue)
* Values should be stored as JSONB 
* This issue would entail just the backend
* Acceptance tests:
  * Can set schema for a particular community (just use JSON, treat as a text blob setting?)
  * Having done this, with a user from that community, can CRUD custom values using convenient, form-friendly methods
  * If schema is changed later, this is handled gracefully
  * Performance should be good, minimize queries to load all this up, perhaps no need to check schema except when editing user

_Originally created by **Tom Smyth** at **2015-12-31 02:37**, migrated from [redmine-#3896](https://redmine.sassafras.coop/issues/3896)_

**Comment by smoyth** [comment]
* **Priority** changed from _3_ to _2_

_By **Tom Smyth** at **2016-01-04 08:05**_

**Comment by smoyth** [comment]
* **Subject** changed from _Community settings_ to _Settings/custom fields_

_By **Tom Smyth** at **2016-04-26 23:48**_

**Comment by smoyth** [comment]
* **Category** set to _Public Release_

_By **Tom Smyth** at **2016-05-22 21:44**_

**Comment by smoyth** [comment]
* **Priority** changed from _2_ to _4_

_By **Tom Smyth** at **2016-09-08 06:05**_

**Comment by smoyth** [comment]
* **Subject** changed from _Settings/custom fields_ to _Custom fields_
  *  **Description** updated ([diff](https://redmine.sassafras.coop/journals/17111/diff?detail_id=17954 "View differences"))
  *  **Category** deleted ( ~~ _Public Release_~~ )
  *  **Estimate** changed from _3.00 h_ to _8.00 h_

_By **Tom Smyth** at **2016-10-23 18:16**_

**Comment by smoyth** [comment]
* **Description** updated ([diff](https://redmine.sassafras.coop/journals/17112/diff?detail_id=17957 "View differences"))

_By **Tom Smyth** at **2016-10-23 18:35**_

**Comment by smoyth** [comment]
Update: this would be a good way to allow personal pronouns. Approach one seems less sensible now that we're growing. We want communities to be able to make this change by themselves. We already have a custom field library for settings. Some thoughts:

* Could make these into custom fields:
    * Allergies
    * Doctor Info
    * Medical Info (textarea)
    * School (for kids)
* Also, for household:
    * Garage Number(s)
    * Extra Unit Keyholders
* Need:
    * Ability to add hint
    * Ability to specify text vs string
    * Ability to have special fields for kids only
    * Migration to move existing things into json blob

Maybe easiest way to do this is with a YML blob for a spec, for now. Editable by admins only. Validation on save.
