### ISSUE TITLE
Enable blanking out of a posted menu

### ISSUE THREAD

**Issue by kenatsun** [gather-community/gather#720]
I'm trying to swap chief cooks jobs with someone.  I have already posted the menu for my meal; my swap partner has not posted hers.  My current meal looks (in part) like this:

![image](https://user-images.githubusercontent.com/316892/72691341-9c7a9f80-3af2-11ea-89d6-08160b261af4.png)

I try to fix this by putting in my swap partner's name as chief cook, then blanking out all the fields from "Title" down thru all the "Allergens".  I Save.  I get "Please review the problems below", which look like this:

![image](https://user-images.githubusercontent.com/316892/72691443-6ab60880-3af3-11ea-8f2a-7cdc1d33bd57.png)

Of course I can stick in some title and entree like "menu to come" and check "none" for allergens.  But this is ugly, and it probably means my trade partner won't get auto-nagged to post her menu.  Moreover:  I tried this,..

![image](https://user-images.githubusercontent.com/316892/72691712-7a365100-3af5-11ea-8cf6-1cfbdf79e0f5.png)

...and got this:

![image](https://user-images.githubusercontent.com/316892/72691748-ba95cf00-3af5-11ea-9be7-4cc37fa3861a.png)

Gather had re-checked all the allergens that I had un-checked, and then it rejected the transaction because I can't say "none" when other allergens are checked.

I trust what's needed to support this use case are clear.  If not, RSVP.

**Comment by smoyth** [comment]
@kenatsun Did you try blanking all menu boxes and all allergen checkboxes, including 'None of these'?

**Comment by kenatsun** [comment]
I *think *I tried that - blanking everything including "None" would be my
first instinct.  But I'm not sure.  Alas, I can't test it any more on the
production instance, because my trading partner entered her menu today.
Maybe someone could test it on a test instance?  And that way works, please
cancel this ticket.

**Comment by smoyth** [comment]
I confirm this was broken. Should be fixed now. Thanks Ken.

**Comment by kenatsun** [comment]
And thanks to you!
