### ISSUE TITLE
Add jitsi integration to Gather

### ISSUE THREAD

**Issue by leilatite** [gather-community/gather#745]
It would be awesome if we could enable some kind of community-wide video and phone conferencing into Gather. Would it be possible to enable something with [jitsi](https://community.jitsi.org/)? Then we could post community meeting events on a common calendar.

**Comment by smoyth** [comment]
I hear Jitsi doesn't work so great with more than 8-10 people. My current recommendation is a Zoom subscription and then you can add the personal meeting room as a resource in Gather. I do have a plan to add a URL field in the resource form so you can add a URL for virtual resources.

**Comment by leilatite** [comment]
I'm fine with closing this as the functionality will be (mostly) covered by #742. I heard jitsi can handle up to 35 people, but I haven't tried it. I despise Zoom, and hate the idea of the community having to pay them money.

**Comment by smoyth** [comment]
Well let me know what kind of luck you have with Jitsi or another
alternative. I'm not against it, I have just heard about the Jitsi
scalability issue from many people.
