### ISSUE TITLE
New member E-mail address in profile doesn't sync to Mailman

### ISSUE THREAD

**Issue by leilatite** [gather-community/gather#844]
Reported by Todd Lewis of Shepherd Village via email on 2021-07-06. A change of Mike Binder’s E-mail address from mbinder@ at reality-alt.com to mike.binder.61 at gmail.com in his Gather profile did not sync or propagate as expected to Mailman.

Please trigger the sync or propagation task that will update Mike Binder’s E-mail address where Mike Binder occurs in Mailman, and check to see whether this observed lack of sync or propagation may be a broader issue needing attention.

The new address is already in the mailman database, but in a weird state.

Memory helper:
irb(main):006:0> Groups::Mailman::Api.instance.send(:request, "addresses/mike.binder.61@gmail.com").send(:json)
=> {"email"=>"mike.binder.61@gmail.com", "original_email"=>"mike.binder.61@gmail.com", "registered_on"=>"2021-02-05T01:42:09.038942", "self_link"=>"http://localhost:8001/3.1/addresses/mike.binder.61@gmail.com", "http_etag"=>"\"3f11c8ba017a53d1d9f6ae307b1d2381d298013f\""}

**Comment by smoyte** [comment]
Closing this as it's super old. If it happens again we can try to dbug.
