### ISSUE TITLE
Page failed with state 503

### ISSUE THREAD

**Issue by KittyCake** [gather-community/gather#849]
Gather unexpectedly failed with state 503.
Same issue happened with my friend in same gather town.

<img width="454" alt="螢幕快照 2021-07-16 上午11 37 59" src="https://user-images.githubusercontent.com/11503196/125888248-d379e0a3-68f4-4823-8d11-362afa91cb32.png">

**Comment by smoyth** [comment]
Hi there. This doesn't look like the right Gather project...

**Comment by KittyCake** [comment]
Oops, I feel very sorry!
