### ISSUE TITLE
editing household information from the Profile edit page

### ISSUE THREAD

**Issue by gdylee88** [gather-community/gather#878]
It looks like changes to the household section are working, except with the unit field,
Changing the unit information directly from the Household page works.

**Comment by smoyth** [comment]
Hi @gdylee88! I am not able to reproduce this bug. Could please provide step by step instructions on how to reproduce this? Thanks!

**Comment by smoyth** [comment]
Good catch Godfrey! Should be fixed now. Please try it out.
