### ISSUE TITLE
List Archive and List Panel links not working

### ISSUE THREAD

**Issue by gdylee88** [gather-community/gather#978]
Ravens Crossing (https://ravenscrossing.gather.coop/)
Godfrey Lee

When I click on the links "List Archive.List Panel" I get an error 500

We're sorry, but something went wrong.

This is an unexpected system error. Gather support staff have been notified.

URL: https://gather.coop/sso?sso=bm9uY2U9MmRiN2FjOGEwNzMyMzAzMWQ3MThlZTExNzRhZmY0NDMmcmV0dXJuX3Nzb191cmw9aHR0cHM6Ly9tYWlsbWFuLmdhdGhlci5jb29wL3Nzby9sb2dpbiZjdXN0b20ubmV4dD0vcG9zdG9yaXVzL2xpc3RzL2V4dGVybmFsLWNvbW0ucmF2ZW5zY3Jvc3NpbmcuZ2F0aGVyLmNvb3Av&sig=a9d23b80a5868e89215848fdcf0b0ade51d264caea9f6384b0139d93d6bc4e5d

This has been at least 2 days that way.

**Comment by smoyte** [comment]
Should be fixed now. Sorry for the trouble. I was working on the single sign on code the other day and broke something.
